### PR TITLE
add public beta links to README.md

### PR DESCRIPTION
**Pull request by webbrowser11**
yeah so umm.... merge if you want sb3 patching might be done here in the future.

### CODE REVIEW

**Comment by webbrowser11** [comment]
also anyone notice microboy hasn't updated coffeOS in a whole month now

**Comment by ScratchFakemon** [comment]
# maybe

**Comment by webbrowser11** [comment]
okay

**Comment by webbrowser11** [comment]
bruh wait i might wanna fix that windows thing or whatever

**Comment by ScratchFakemon** [comment]
do we really need the links, though? They're betas and you can just load them into TurboWarp or most other Scratch mods

**Comment by webbrowser11** [comment]
its easier to click the link and then run then to open a scratch mod website click see inside import the sb3 wait like 20 seconds for it to import and then finally run the project

**Comment by ScratchFakemon** [comment]
well they're public betas and the links to the full releases will be in the project and who cares

**Comment by webbrowser11** [comment]
so i took 3 hours making this over time and you get rid of it?

**Comment by ScratchFakemon** [comment]
I might think about it

**Pull request closed without merging**
